### ISSUE TITLE
Roteiros turísticos

### ISSUE THREAD

**Issue by Jesinski** [Jesinski/MyFlight-Trabalho-Final#9]
O programa deve sugerir um roteiro turístico a partir de um conjunto de cidades. Com os requisitos:

- [x]   Deve passar por todas as cidades do conjunto e terminar na cidade de origem;
- [x]   Voo entre cidades com no máximo 2 conexões;
- [x]   Não deve repetir aeroporto (exceto o aeroporto de origem da viagem)

Essa issue é referencia ao seguinte requisito:
> Dado um conjunto de cidades, propor um roteiro turístico passando por cada uma das
> cidades e retornando para cidade de origem. Nenhum voo entre duas cidades deve ter
> mais de duas conexões e não deve ser utilizado o mesmo aeroporto mais de uma vez
> (exceto o de origem da viagem).

**Comment by Notdutra** [comment]
feito
